language: ruby
rvm:
  - 2.2.2
cache: bundler
addons:
  postgresql: "9.4"
env:
- DB=postgresql
bundler_args: --without production
before_script:
  - psql -c 'create database card_mine_backend_test;' -U postgres
script:
  - bin/rake db:migrate RAILS_ENV=test
  - bin/rake
